name: chat_widget
description: Chat for flutter
version: 0.0.1
author: SeriusDavid
homepage: https://github.com/SeriusDavid/chat-widget

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # FOR WEBSOCKET IN CHAT
  web_socket_channel: ^2.2.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
